#!/bin/bash

# Check if correct number of arguments are passed
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 [format] [download_directory]"
  exit 1
fi

# Define arguments
format=$1
download_directory=$2

# Check if download directory exists, if not create it
if [ ! -d "$download_directory" ]; then
  mkdir -p "$download_directory"
fi

# Define language codes
language_codes=(
  "nl"
  "pl"
  "zh-tw"
  "it"
  "sq"
  "es"
  "en-ca"
  "de"
  "en-au"
  "pt-br"
  "en-nz"
  "fr"
  "ja"
  "sv"
  "ru"
  "zh-cn"
  "ro"
  "es-mx"
  "es-ar"
  "uk"
  "pt"
  "es-ve"
  "en-gb"
  "fi"
  "bg"
  "eu"
  "hu"
  "da"
  "ca"
  "cy"
  "nb"
  "el"
  "hr"
  "et"
  "sk"
  "sr"
  "az"
  "tr"
  "he"
  "bn"
  "cs"
  "is"
  "sl"
  "ko"
  "id"
  "ary"
  "lt"
  "es-cl"
  "de-formal"
  "fa"
  "vi"
  "nn"
  "ar"
  "lv"
  "th"
  "ms"
  "nl-formal"
  "es-pe"
  "de-ch"
  "bs"
  "es-co"
  "hy"
  "mk"
  "ta"
  "tl"
  "gl"
  "kn"
  "af"
  "es-ve"
)

# Loop through each language code and download the corresponding translation file
for code in "${language_codes[@]}"; do
  echo "Downloading $code..."
  curl -o "$download_directory/$code.$format" "https://translate.wordpress.org/projects/wp-plugins/fakerpress/stable/$code/default/export-translations/?format=$format"
  sleep 3
done
