<?php
/**
 * Tests for the Term module flag / fetch / delete (erase) cycle.
 *
 * @since 0.9.2
 *
 * @package FakerPress\Tests\Module
 */

namespace FakerPress\Tests\Module;

use FakerPress\Module\Term;

/**
 * Class TermEraseTest
 *
 * Regression coverage for issue #219: "Erase faked data" did not delete generated categories,
 * because creation flagged terms under the option `fakerpress.module_flag.terms` (plural) while
 * fetch()/delete() read and cleared the singular `fakerpress.module_flag.term`.
 *
 * @since 0.9.2
 */
class TermEraseTest extends \Codeception\TestCase\WPTestCase {

	/**
	 * Create a flagged term through the module, mirroring real generation.
	 *
	 * @param string $taxonomy Taxonomy slug.
	 *
	 * @return int The created term ID.
	 */
	private function create_flagged_term( string $taxonomy ): int {
		$module = new Term();

		return (int) $module->filter_save_response(
			null,
			[
				'name'        => 'FP Erase ' . $taxonomy . ' ' . wp_generate_password( 6, false ),
				'taxonomy'    => $taxonomy,
				'description' => 'Generated by FakerPress test.',
				'parent_term' => 0,
			],
			$module
		);
	}

	/**
	 * fetch() must return the terms that creation flagged (same option key on both sides).
	 *
	 * @test
	 */
	public function it_should_fetch_flagged_terms(): void {
		$term_id = $this->create_flagged_term( 'category' );

		$flagged = Term::fetch();

		$this->assertNotEmpty( $flagged, 'fetch() should return the flagged terms, not an empty array.' );
		$this->assertArrayHasKey( 'category', $flagged );
		$this->assertContains( $term_id, $flagged['category'] );
	}

	/**
	 * delete() must remove the flagged terms and clear the flag option — the full erase path.
	 *
	 * @test
	 */
	public function it_should_delete_flagged_terms_and_clear_the_option(): void {
		$category_id = $this->create_flagged_term( 'category' );
		$tag_id      = $this->create_flagged_term( 'post_tag' );

		$items = Term::fetch();
		$this->assertNotEmpty( $items );

		Term::delete( $items );

		$this->assertNull( get_term( $category_id ), 'Generated category should be deleted.' );
		$this->assertNull( get_term( $tag_id ), 'Generated tag should be deleted.' );
		$this->assertEmpty( Term::fetch(), 'The flag option should be cleared after delete().' );
	}
}
