name: 'Readme Auto Generator'
on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Generate Readme
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Generate readme files
      run: bun run dev/generate-readme.ts

    - name: Commit readme file
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Apply readme.md Changes
        branch: main
        file_pattern: readme.md

    - name: Commit readme.php file
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Apply data/readme.php Changes
        branch: main
        file_pattern: src/data/readme.php
